config/routes.rb
InventorySystem::Application.routes.draw do
  resources :inventories

end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  validates_presence_of :title
  validates_presence_of :description
  validates_presence_of :quantity
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  def index
    @items = Inventory.all
  end

  def new
    @item = Inventory.new
  end

  def create
    @item = Inventory.new(item_params)
    if @item.save
      redirect_to @item, notice: "Item was successfully saved"
    else
      render action: 'new'
    end
  end

  def show
    @item = Inventory.find(params[:id])
  end

  private
  def item_params
    params.require(:inventory).permit(:title, :description, :quantity)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/inventories/index.html.erb
<h1>Inventory</h1>
<%= link_to "New Item", new_inventory_path, class: "button radius" %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Quantity</th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.title %></td>
        <td><%= item.description %></td>
        <td><%= item.quantity %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/inventories/new.html.erb
<h1>Create New Item</h1>
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label(:title, "Title") %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label(:description, "Description") %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label(:quantity, "Quantity") %><br>
    <%= f.text_field :quantity %>
  </div>

  <div class="action">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/inventories/show.html.erb
<p id="notice"><%= notice %></p>

Title:       <%= @item.title %> <br/>
Description: <%= @item.description %> <br/>
Quantity:    <%= @item.quantity %> <br/><br/>

<%= link_to 'Edit', edit_inventory_path(@item) %> |
<%= link_to 'Inventory', inventories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InventorySystem</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>